"""create status table

Revision ID: b0fd2d114b13
Revises: a8d87bf43427
Create Date: 2023-10-23 13:30:32.529575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0fd2d114b13'
down_revision = 'a8d87bf43427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('statusId', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['description'], ['task.description'], ),
    sa.PrimaryKeyConstraint('statusId')
    )
    op.add_column('task', sa.Column('projectId', sa.Integer(), nullable=False))
    op.add_column('task', sa.Column('statusId', sa.Integer(), nullable=False))
    op.add_column('task', sa.Column('deadline', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'status', ['statusId'], ['statusId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'deadline')
    op.drop_column('task', 'statusId')
    op.drop_column('task', 'projectId')
    op.drop_table('status')
    # ### end Alembic commands ###
